name: flutter_utils
description: "Flutter utilties for common tasks."
version: 0.0.1
repository: https://github.com/mcquenji/flutter_utils
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.4

dependency_overrides:
  flutter_modular:
    git:
      url: https://github.com/necodeIT/modular.git
      path: flutter_modular

dev_dependencies:
  architecture_linter: ^0.2.2
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
